// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtSTBPi0057iyQgnc8z8xB3solNqxd_xU',
    appId: '1:692677003371:web:2c2f2cb757ea3f3788c92e',
    messagingSenderId: '692677003371',
    projectId: 'brahma-4517',
    authDomain: 'brahma-4517.firebaseapp.com',
    storageBucket: 'brahma-4517.appspot.com',
    measurementId: 'G-4VEWEHDLHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtj2nOVIzk3ZLN0iBDxqP8DyqIaHFmE7s',
    appId: '1:692677003371:android:3c388abe7208029188c92e',
    messagingSenderId: '692677003371',
    projectId: 'brahma-4517',
    storageBucket: 'brahma-4517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUGqanJ0ZTrIFFIkeDItbadHtV8YurQ-Y',
    appId: '1:692677003371:ios:e6e92f7fd53e8a6588c92e',
    messagingSenderId: '692677003371',
    projectId: 'brahma-4517',
    storageBucket: 'brahma-4517.appspot.com',
    iosClientId: '692677003371-5vtmkro8vp45uiqp2jvsalfe8b3d9rqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.brahma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUGqanJ0ZTrIFFIkeDItbadHtV8YurQ-Y',
    appId: '1:692677003371:ios:e6e92f7fd53e8a6588c92e',
    messagingSenderId: '692677003371',
    projectId: 'brahma-4517',
    storageBucket: 'brahma-4517.appspot.com',
    iosClientId: '692677003371-5vtmkro8vp45uiqp2jvsalfe8b3d9rqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.brahma',
  );
}
